# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: michael.feher@algorand.foundation
author_name: Michael Feher
contract_name: evanescent
deployment_language: python
preset_name: starter
project_name: d13-toolkit

